# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-mp3info}
  s.version = "0.6.13"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Guillaume Pierronnet"]
  s.date = %q{2010-09-06}
  s.description = %q{ruby-mp3info is a pure-ruby library to retrieve low level
            informations on mp3 files and manipulate id3v1 and id3v2 tags}
  s.email = %q{andrew.hay.kurtz@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.txt",
     "LICENSE",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "install.rb",
     "lib/mp3info.rb",
     "lib/mp3info/extension_modules.rb",
     "lib/mp3info/id3v2.rb",
     "lib/ruby-mp3info.rb",
     "test/helper.rb",
     "test/test_ruby-mp3info.rb"
  ]
  s.homepage = %q{http://github.com/gzuki/ruby-mp3info}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{ruby-mp3info is a pure-ruby library to retrieve low level informations on mp3 files and manipulate id3v1 and id3v2 tags}
  s.test_files = [
    "test/helper.rb",
     "test/test_ruby-mp3info.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

